### ISSUE TITLE
Screen will dim during gameplay with a 3rd party controller

### ISSUE THREAD

**Issue by rdlf4** [Hydr8gon/VitaControl#11]
I've got two issues, one of them is kinda annoying.
Controller in question is the GameSir T4 PRO. It's working but it required a tweak right after pairing it with my OG PHAT Vita 1000.
Regardless of which Standby mode option I choose (from Power Save settings) the display will dim during gameplay, meaning that even though I'm using my 3rd party controller, to the OS, the Vita is doing nothing. I try pausing the game once that happens, and press the "ps button" on my controller. Sometimes this works but mostly it won't.

Another issue is this: all of my controller buttons are recognized and properly assigned to the Vita, as expected.
Pressing pause pauses the game, and the ps button gets me out of the game. Curiously, holding the ps button down and pressing start won't screenshot.

Out of context but worth pointing out: To my surprise L and R do their job while switching apps, but once I'm playing NFS: Most Wanted, then L2 and R2 are used to brake and throttle, respectively. I'm not sure why that is and as far as I've checked I'm not running any plugin that makes my Vita behave like a PSTV, but I love that that's just how it is by default! Now we just need to make the screen not dim while gaming on a 3rd party controller and we'll be gold.

**Comment by Hydr8gon** [comment]
Regarding the screen dimming, follow [this guide](https://gbatemp.net/threads/disable-auto-dim-on-ps-vita-with-registry-editor-and-henkaku.441890/) for a workaround. I might look into ways this can be done automatically with VitaControl, but for now it's better than nothing. As for the screenshot functionality, I'll have to look into it. I had to implement the PS button differently than the other buttons, so I wouldn't be surprised if that messes things up.

**Comment by Hydr8gon** [comment]
This is now fixed with commit faa6324.
