### ISSUE TITLE
Nintendo Switch Pro driver only

### ISSUE THREAD

**Issue by zerofalcon** [Hydr8gon/VitaControl#26]
First of all, thank you for this plugin.

My issue sounds more like a petition (sorry for that). Im using minivitatv to use more controllers for multiplayer games.
My original ps3 dualshock controller works fine, same as my original ns pro. When using minivitatv conflicts arise with my DS3 controller using your plugin, if only your plugin could be build with only the nintendo switch pro driver Im sure it will resolve the issue.
Thanks in advanced.

**Comment by Hydr8gon** [comment]
Here's a build with everything except the Switch controller disabled:
[vitacontrol.zip](https://github.com/Hydr8gon/VitaControl/files/15493419/vitacontrol.zip)

**Comment by zerofalcon** [comment]
I made some tests and it works nice! thanks a lot for fulfilling my petition. Issue can be closed now.
