### ISSUE TITLE
Can't download build

### ISSUE THREAD

**Issue by SpaceGuineaProductions** [Hydr8gon/VitaControl#3]
Maybe I just don't know how any of this works but the build seems to have expired.

**Comment by Hydr8gon** [comment]
Yeah, that's my bad. I need to update the autobuild to publish releases, so the downloads don't expire. I also need to look at that pull request that's been sitting for nearly a month now. I haven't really touched this project since I made it; I'll try to make time tonight.

**Comment by Hydr8gon** [comment]
Alright, there we go. Now you can find the latest build [here](https://github.com/Hydr8gon/VitaControl/releases), and it won't expire. Sorry about that!

**Comment by delipunch** [comment]
> Alright, there we go. Now you can find the latest build [here](https://github.com/Hydr8gon/VitaControl/releases), and it won't expire. Sorry about that!

That build has expired. I followed the link, but there were no releases on that page. I tried looking in the Wayback Machine, but the actual build wasn't archived there even though the release page was.

**Comment by Hydr8gon** [comment]
Sorry, the build is up now. I've been having issues with releases randomly not publishing.
